version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - FLASK_ENV=production
    networks:
      - chatbotnet

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - chatbotnet
    volumes:
      - ollama_models:/root/.ollama

networks:
  chatbotnet:

volumes:
  ollama_models:
