version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    networks:
      - chatbotnet
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - chatbotnet
    volumes:
      - ollama_models:/root/.ollama
    # No command override — it should run as the Ollama server by default

networks:
  chatbotnet:

volumes:
  ollama_models:
